/*!
 * @file inspector_context.h
 * @brief Context wrapper that owns object memory and exposes inspector APIs.
 *
 * The inspector_context_t allocates and owns the target object memory so callers
 * can safely obtain stable pointers to the contained object. It internally
 * creates and binds an `inspector_t` instance; convenience wrapper functions
 * forward common inspector queries to that internal instance.
 */

#ifndef INSPECTOR_CONTEXT_H
#define INSPECTOR_CONTEXT_H

#include <stddef.h>

/** Opaque context type that owns data and an internal inspector. */
typedef struct inspector_context_t inspector_context_t;

/** Forward declaration for struct metadata generated by the DSL. */
typedef struct inspector_struct_info_t inspector_struct_info_t;

/**
 * @brief Create a new inspector context for the given struct metadata.
 * @param info Pointer to generated `inspector_struct_info_t` describing the type.
 * @param prefix Optional prefix string to use when binding member names; pass
 *               NULL or empty string to bind without a prefix.
 * @return Pointer to a newly allocated inspector_context_t, or NULL on failure.
 */
inspector_context_t* inspector_context_create(const inspector_struct_info_t* info, const char* prefix);

/**
 * @brief Destroy an inspector context and free owned memory.
 * @param ctx Context returned by inspector_context_create.
 */
void inspector_context_destroy(inspector_context_t* ctx);

/**
 * @brief Update the owned object memory by copying from user-provided data.
 * @param ctx Inspector context.
 * @param data Pointer to source data of the same type described by `info`.
 * @return 0 on success, non-zero on error.
 */
int inspector_context_update(inspector_context_t* ctx, const void* data);

/**
 * @brief Get a const pointer to the owned object memory.
 * @param ctx Inspector context.
 * @return Pointer to the owned data, or NULL if ctx is NULL.
 */
const void* inspector_context_get_data(const inspector_context_t* ctx);

/* Convenience wrappers that forward to the internal inspector_t. All wrappers
 * perform NULL checks on the provided context. */

/**
 * @brief Check whether the internal inspector contains a named member.
 * @param ctx Inspector context.
 * @param name Member name to query.
 * @return Non-zero if found, zero otherwise.
 */
int inspector_context_contains(const inspector_context_t* ctx, const char* name);

/**
 * @brief Get the type name of a registered member.
 * @param ctx Inspector context.
 * @param name Member name to query.
 * @return Pointer to the type name string, or NULL if not found.
 */
const char* inspector_context_type(const inspector_context_t* ctx, const char* name);

/**
 * @brief Get the pointer registered for a named member from the internal inspector.
 * @param ctx Inspector context.
 * @param name Member name to query.
 * @return Pointer to the registered object, or NULL if not found.
 */
void* inspector_context_get(inspector_context_t* ctx, const char* name);

/**
 * @brief Get number of members registered in the internal inspector.
 * @param ctx Inspector context.
 * @return Count of registered members, or 0 for NULL ctx.
 */
int inspector_context_size(const inspector_context_t* ctx);

/**
 * @brief Get the name of the member at the given index.
 * @param ctx Inspector context.
 * @param index Zero-based index of the member.
 * @return Pointer to the name string, or NULL if index is out of range.
 */
const char* inspector_context_name_at(const inspector_context_t* ctx, int index);

/**
 * @brief Get the type name of the member at the given index.
 * @param ctx Inspector context.
 * @param index Zero-based index of the member.
 * @return Pointer to the type name string, or NULL if index is out of range.
 */
const char* inspector_context_type_at(const inspector_context_t* ctx, int index);

#endif /* INSPECTOR_CONTEXT_H */
